module.exports = [
  
    {normal: 'a', flipped:'ɐ'},
    {normal: 'b', flipped:'q'},
    {normal: 'c', flipped:'ɔ'},
    {normal: 'd', flipped:'p'},
    {normal: 'e', flipped:'ǝ'},
    {normal: 'f', flipped:'ɟ'},
    {normal: 'g', flipped:'ƃ'},
    {normal: 'h', flipped:'ɥ'},
    {normal: 'i', flipped:'ı'},
    {normal: 'j', flipped:'ɾ'},
    {normal: 'k', flipped:'ʞ'},
    {normal: 'l', flipped:'ʃ'},
    {normal: 'm', flipped:'ɯ'},
    {normal: 'n', flipped:'u'},
    {normal: 'o', flipped:'o'},
    {normal: 'p', flipped:'d'},
    {normal: 'q', flipped:'b'},
    {normal: 'r', flipped:'ɹ'},
    {normal: 's', flipped:'s'},
    {normal: 't', flipped:'ʇ'},
    {normal: 'u', flipped:'n'},
    {normal: 'v', flipped:'ʌ'},
    {normal: 'w', flipped:'ʍ'},
    {normal: 'x', flipped:'x'},
    {normal: 'y', flipped:'ʎ'},
    {normal: 'z', flipped:'z'},
    
    {normal: 'A', flipped: '∀'},
    {normal: 'B', flipped: '𐐒'},
    {normal: 'C', flipped: 'Ɔ'},
    {normal: 'D', flipped: 'ᗡ'},
    {normal: 'E', flipped: 'Ǝ'},
    {normal: 'F', flipped: 'Ⅎ'},
    {normal: 'G', flipped: '⅁'},
    {normal: 'H', flipped: 'H'},
    {normal: 'I', flipped: 'I'},
    {normal: 'J', flipped: 'ſ'},
    {normal: 'K', flipped: '⋊'},
    {normal: 'L', flipped: '⅂'},
    {normal: 'M', flipped: 'W'},
    {normal: 'N', flipped: 'N'},
    {normal: 'O', flipped: 'O'},
    {normal: 'P', flipped: 'Ԁ'},
    {normal: 'Q', flipped: 'Ό'},
    {normal: 'R', flipped: 'ᴚ'},
    {normal: 'S', flipped: 'S'},
    {normal: 'T', flipped: '⊥'},
    {normal: 'U', flipped: '∩'},
    {normal: 'V', flipped: 'Λ'},
    {normal: 'W', flipped: 'M'},
    {normal: 'X', flipped: 'X'},
    {normal: 'Y', flipped: '⅄'},
    {normal: 'Z', flipped: 'Z'}
    
  ];
